### ISSUE TITLE
No database to test the files

### ISSUE THREAD

**Issue by patel-dhaval** [Arvindiyer/wallstreet#1]
The files doesn't have the database file which is needed to test the developed project.
User Interface is fantastic !

**Comment by Arvindiyer** [comment]
@patel-dhaval 
Added the database files.Anything else do ping me.

**Comment by patel-dhaval** [comment]
Where should I ping you ? 
Thanks Btw ! :)

Edit: Having a problem regarding to login ! Im not getting the login page :(

**Comment by Arvindiyer** [comment]
@patel-dhaval  Ping me at 9687181987
